"use client"

import { Loader2 } from "lucide-react"
import { useTransition } from "react"
import { toast } from "sonner"

import { Button } from "@/features/shadcn/components/ui/button"
import { createStoreAction } from "@/features/stores/actions/create-store.action"
import { CreateStoreFormType } from "@/features/stores/schemas"

const BASE_PAYLOAD: CreateStoreFormType = {
    basic_info: {
        name: "Test Store",
        description: "Generated by test button",
        subdomain: "test-store",
    },
    address_info: {
        is_physical_store: false,
    },
    contact_info: {},
    settings: {
        is_open_24_hours: true,
        attention_dates: [],
    },
    shipping_info: {
        offers_delivery: false,
    },
    payment_info: {
        payment_methods: [],
    },
}

const TEST_PAYLOADS: { name: string; payload: CreateStoreFormType }[] = [
    {
        name: "Standard Full",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Standard Full Store" },
            address_info: { is_physical_store: true, address: "Main St 123", city: "City", province: "State", country: "Country" },
            payment_info: {
                payment_methods: [
                    { name: "Billetera", type: "billetera_virtual", cbu_cvu: "123456", commission_percent: 0, commission_amount: 0 },
                    { name: "Efectivo", type: "efectivo", commission_percent: 0, commission_amount: 0 }
                ]
            },
            shipping_info: { offers_delivery: true, methods: [{ providers: ["Own Delivery"], deliveryPrice: "500" }] }
        }
    },
    {
        name: "Minimal",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Minimal Store" }
        }
    },
    {
        name: "Physical Only",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Physical Store" },
            address_info: { is_physical_store: true, address: "Physical St 1", city: "City", province: "State", country: "Country" }
        }
    },
    {
        name: "Delivery Only",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Delivery Store" },
            shipping_info: { offers_delivery: true, methods: [{ providers: ["Own Delivery"], deliveryPrice: "1000" }] }
        }
    },
    {
        name: "Cash Only",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Cash Only Store" },
            payment_info: {
                payment_methods: [
                    { name: "Efectivo", type: "efectivo", commission_percent: 0, commission_amount: 0 }
                ]
            }
        }
    },
    {
        name: "Multiple Payments",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Multi Payment Store" },
            payment_info: {
                payment_methods: [
                    { name: "Efectivo", type: "efectivo", commission_percent: 0, commission_amount: 0 },
                    { name: "Transferencia", type: "transferencia", cbu_cvu: "111222", commission_percent: 0, commission_amount: 0 },
                    { name: "MP", commission_percent: 5, commission_amount: 0 , type : "billetera_virtual"},
                    { name: "Billetera", type: "billetera_virtual", cbu_cvu: "333444", commission_percent: 0, commission_amount: 0 }
                ]
            }
        }
    },
    {
        name: "24/7 Open",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "24-7 Store" },
            settings: { is_open_24_hours: true, attention_dates: [] }
        }
    },
    {
        name: "Custom Hours",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Custom Hours Store" },
            settings: { 
                is_open_24_hours: false,
                attention_dates: [
                    { days: ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes"], startTime: "09:00", endTime: "18:00" }
                ]
            }
        }
    },
    {
        name: "Social Media Rich",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Social Store" },
            contact_info: {
                phones: [{ phone: "12345678", is_primary: true }],
                emails: [{ email: "test@store.com", is_primary: true }],
                social_media: [
                    { url: "https://instagram.com/store", is_primary: true },
                    { url: "https://facebook.com/store", is_primary: false }
                ]
            }
        }
    },
    {
        name: "Complex Shipping",
        payload: {
            ...BASE_PAYLOAD,
            basic_info: { ...BASE_PAYLOAD.basic_info, name: "Complex Ship Store" },
            shipping_info: {
                offers_delivery: true,
                methods: [
                    { providers: ["Own Delivery"], deliveryPrice: "500", minPurchase: "2000", freeShippingMin: "10000" },
                    { providers: ["Pickup"], deliveryPrice: "0" }
                ]
            }
        }
    }
]

export function TestStoreCreator({ userId }: { userId: number }) {
  const [isPending, startTransition] = useTransition()

  const handleCreate = (payload: CreateStoreFormType, name: string) => {
    const uniqueId = Math.floor(Math.random() * 10000)
    const uniquePayload = {
        ...payload,
        basic_info: {
            ...payload.basic_info,
            name: `${payload.basic_info.name} ${uniqueId}`,
            subdomain: `${payload.basic_info.subdomain}-${uniqueId}`
        }
    }

    startTransition(async () => {
      const result = await createStoreAction(uniquePayload, userId)
      if (result.hasError) {
        toast.error(`Error creating ${name}: ${result.message}`)
      } else {
        toast.success(`${name} created successfully!`)
      }
    })
  }

  return (
    <div className="grid grid-cols-2 md:grid-cols-5 gap-2 p-4 border rounded-lg mb-4 bg-background">
      <h3 className="col-span-2 md:col-span-5 font-bold mb-2">Test Store Creators</h3>
      {TEST_PAYLOADS.map((test) => (
        <Button 
          key={test.name} 
          variant="outline" 
          size="sm"
          disabled={isPending}
          onClick={() => handleCreate(test.payload, test.name)}
          className="w-full"
        >
            {isPending ? <Loader2 className="animate-spin mr-2 h-4 w-4"/> : null}
          {test.name}
        </Button>
      ))}
    </div>
  )
}

