export const HEADER_CONSTANTS = {
  SCROLL_TRIGGER_ZONE: 100,
  HEADER_OFFSET_DESKTOP: 80,
  HEADER_OFFSET_MOBILE: 56,
  SCROLL_THRESHOLD: 5,
  DRAWER_CLOSE_DELAY: 300,
  ANIMATION: {
    HEADER_ENTER_DURATION: 0.6,
    NAV_ENTER_DELAY: 0.7,
    ACTIONS_ENTER_DELAY: 0.8,
  },
} as const;

export type HeaderConstants = typeof HEADER_CONSTANTS;

export const DRAWER_CLOSE_DELAY = HEADER_CONSTANTS.DRAWER_CLOSE_DELAY;


